export const InterfaceTypes = {
	strip: 0,
	bus: 1,
};

export enum StripProperties {
	Mono = "Mono",
	Mute = "Mute",
	Solo = "Solo",
	MC = "MC",
	Gain = "Gain",
	GainLayer0 = "GainLayer[0]",
	GainLayer1 = "GainLayer[1]",
	GainLayer2 = "GainLayer[2]",
	GainLayer3 = "GainLayer[3]",
	GainLayer4 = "GainLayer[4]",
	GainLayer5 = "GainLayer[5]",
	GainLayer6 = "GainLayer[6]",
	GainLayer7 = "GainLayer[7]",
	Pan_x = "Pan_x",
	Pan_y = "Pan_y",
	Color_x = "Color_x",
	Color_y = "Color_y",
	fx_x = "fx_x",
	fx_y = "fx_y",
	Audibility = "Audibility",
	Comp = "Comp",
	CompGainIn = "Comp.GainIn",
	CompRatio = "Comp.Ratio",
	CompThreshold = "Comp.Threshold",
	CompAttack = "Comp.Attack",
	CompRelease = "Comp.Release",
	CompKnee = "Comp.Knee",
	CompGainOut = "Comp.GainOut",
	CompMakeUp = "Comp.MakeUp",
	Gate = "Gate",
	GateThreshold = "Gate.Threshold",
	GateDamping = "Gate.Damping",
	GateBPSidechain = "Gate.BPSidechain",
	GateAttack = "Gate.Attack",
	GateHold = "Gate.Hold",
	GateRelease = "Gate.Release",
	Denoiser = "Denoiser",
	Karaoke = "Karaoke",
	Limit = "Limit",
	EqGain1 = "EqGain1",
	EqGain2 = "EqGain2",
	EqGain3 = "EqGain3",
	Label = "Label",
	A1 = "A1",
	A2 = "A2",
	A3 = "A3",
	A4 = "A4",
	A5 = "A5",
	B1 = "B1",
	B2 = "B2",
	B3 = "B3",
	FadeTo = "FadeTo",
	FadeBy = "FadeBy",
	Reverb = "Reverb",
	Delay = "Delay",
	Fx1 = "Fx1",
	Fx2 = "Fx2",
	PostReverb = "PostReverb",
	PostDelay = "PostDelay",
	PostFx1 = "PostFx1",
	PostFx2 = "PostFx2",
	EQon = "EQ.on",
	EQAB = "EQ.AB",
	AppGain = "AppGain",
	APpMute = "AppMute",
	DeviceName = "device.name",
	DeviceSR = "device.sr",
	DeviceWDM = "device.wdm",
	DeviceKS = "device.ks",
	DeviceMME = "device.mme",
	DeviceASIO = "device.asio"
}

export enum BusProperties {
	Mono = "Mono",
	Mute = "Mute",
	EQ = "EQ.on",
	EQon = "EQ.on",
	EQAB = "EQ.AB",
	Gain = "Gain",
	Label = "Label",
	ModeNormal = "mode.normal",
	ModeAmix = "mode.Amix",
	ModeBmix = "mode.Bmix",
	ModeRepeat = "mode.Repeat",
	ModeComposite = "mode.Composite",
	ModeTVMix = "mode.TVMix",
	ModeUpMix21 = "mode.UpMix21",
	ModeUpMix41 = "mode.UpMix41",
	ModeUpMix61 = "mode.UpMix61",
	ModeCenterOnly = "mode.CenterOnly",
	ModeLFEOnly = "mode.LFEOnly",
	ModeRearOnly = "mode.RearOnly",
	FadeTo = "FadeTo",
	FadeBy = "FadeBy",
	Sel = "Sel",
	ReturnReverb = "ReturnReverb",
	ReturnDelay = "ReturnDelay",
	ReturnFx1 = "ReturnFx1",
	ReturnFx2 = "ReturnFx2",
	Monitor = "Monitor",
	DeviceName = "device.name",
	DeviceSR = "device.sr",
	DeviceWDM = "device.wdm",
	DeviceKS = "device.ks",
	DeviceMME = "device.mme",
	DeviceASIO = "device.asio"
}

export enum FXSettings {
	ReverbOn = "Reverb.On",
	ReverbAB = "Reverb.AB",
	DelayOn = "Delay.On",
	DelayAB = "Delay.AB",
}

export enum RecorderProperties {
	Stop = "stop",
	Play = "play",
	Replay = "replay",
	FastForward = "ff",
	Rewind = "req",
	GoTo = "goto",
	A1 = "A1",
	A2 = "A2",
	A3 = "A3",
	A4 = "A4",
	A5 = "A5",
	B1 = "B1",
	B2 = "B2",
	B3 = "B3",
	Record = "record",
	Pause = "pause",
	Load = "load",
	SampleRate = "samplerate",
	ArmStrip0 = "ArmStrip(0)",
	ArmStrip1 = "ArmStrip(1)",
	ArmStrip2 = "ArmStrip(2)",
	ArmStrip3 = "ArmStrip(3)",
	ArmStrip4 = "ArmStrip(4)",
	ArmStrip5 = "ArmStrip(5)",
	ArmStrip6 = "ArmStrip(6)",
	ArmStrip7 = "ArmStrip(7)",
	ArmStrip8 = "ArmStrip(8)",
	ArmBus0 = "ArmBus(0)",
	ArmBus1 = "ArmBus(1)",
	ArmBus2 = "ArmBus(2)",
	ArmBus3 = "ArmBus(3)",
	ArmBus4 = "ArmBus(4)",
	ArmBus5 = "ArmBus(5)",
	ArmBus6 = "ArmBus(6)",
	ArmBus7 = "ArmBus(7)",
	ArmBus8 = "ArmBus(8)",
	ModeRecBus = "mode.recbus",
	ModePlayOnLoad = "mode.PlayOnLoad",
	ModeLoop = "mode.Loop",
	ModeMultiTrack = "mode.MultiTrack",
	BitResolution = "bitResolution",
	Channel = "Channel",
	KBPS = "kbps",
	FileType = "FileType",
	Gain = "Gain"
}

export enum CommandActions {
	Shutdown = "Shutdown",
	Show = "Show",
	Restart = "Restart",
	Eject = "Eject",
	Reset = "Reset",
	Save = "Save",
	Load = "Load",
	Lock = "Lock",
	DialogShowVBANChat = "DialogShow.VBANCHAT"
}

export enum CommandButtons {
	State = "ButtonState",
	StateOnly = "ButtonStateOnly",
	Trigger = "ButtonTrigger",
	Color = "ButtonColor"
}

export enum CommandEqs {
	SaveBus = "EqSaveBus",
	LoadBus = "EqLoadBus",
	SaveStrip = "EqSaveStrip",
	LoadStrip = "EqLoadStrip"
}